# Generated by Django 5.1.3 on 2024-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "min_investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("duration_in_months", models.PositiveIntegerField()),
                ("return_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
