# Generated by Django 5.1.3 on 2024-11-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_name_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
