# Generated by Django 5.1.3 on 2024-11-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentsubscription",
            name="date_of_returns",
            field=models.DateField(blank=True, null=True),
        ),
    ]
