# Generated by Django 5.1.3 on 2024-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_investmentsubscription_date_of_returns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentsubscription",
            name="date_of_returns",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
