# Generated by Django 5.1.3 on 2024-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_investmentsubscription_date_of_returns"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="ledger_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
